CREATE SCHEMA ADMINFREE DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;

CREATE TABLE ADMINFREE.CLIENTES (
  ID_CLIENTE 				  TINYINT	         	NOT NULL AUTO_INCREMENT,
  TOKEN 					      VARCHAR(50)  	NOT NULL,
  NOMBRE 					  VARCHAR(100)	NOT NULL,
  TELEFONOS 				  VARCHAR(50)	 	NULL,
  EMAILS 					      VARCHAR(100)	NULL,
  FECHA_ACTIVACION 	  DATE 		     	NOT NULL,
  FECHA_INACTIVACION DATE 		     	NULL,
  ESTADO 					  TINYINT 	     	NOT NULL,
  PRIMARY KEY (ID_CLIENTE)
);


DELIMITER //
	CREATE PROCEDURE ADMINFREE.PR_ELIMINAR_CLIENTE(IN ID TINYINT,  OUT RESPUESTA VARCHAR(700))
	BEGIN

		/*Manejo de errores*/ 
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			ROLLBACK;
			GET STACKED DIAGNOSTICS CONDITION 1 RESPUESTA = MESSAGE_TEXT;
		END;
		
		/*Inicia transaccion*/ 
		START TRANSACTION; 
		
			/*Se elimina los datos del cliente*/ 
			DELETE FROM ADMINFREE.CLIENTES WHERE ID_CLIENTE = ID;		
		
		/*Fin de transaccion */ 
		COMMIT; 
		
		/*Mandamos 200 si todo salio bien*/ 
		SET RESPUESTA = '200';
	END //
DELIMITER ;