CREATE SCHEMA ADMINFREE DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;

CREATE TABLE ADMINFREE.CLIENTES (
  ID_CLIENTE 				  TINYINT	         	NOT NULL AUTO_INCREMENT,
  TOKEN 					      VARCHAR(50)  	NOT NULL,
  NOMBRE 					  VARCHAR(100)	NOT NULL,
  TELEFONOS 				  VARCHAR(50)	 	NULL,
  EMAILS 					      VARCHAR(100)	NULL,
  FECHA_ACTIVACION 	  DATE 		     	NOT NULL,
  FECHA_INACTIVACION DATE 		     	NULL,
  ESTADO 					  TINYINT 	     	NOT NULL,
  PRIMARY KEY (ID_CLIENTE)
);