/*  
 ***************** CREACION ESQUEMA *******************************
 */ 
CREATE SCHEMA LEARNING_ENGLISH DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;

/* 
 ***************** CREACION DE LAS TABLAS ****************************************
 */ 
CREATE TABLE LEARNING_ENGLISH.SERIES (
	ID_SERIE 				INTEGER			NOT NULL AUTO_INCREMENT,
	NAME 					  	VARCHAR(255)	NOT NULL,
	URL							VARCHAR(255)	NOT NULL,
	IMG							BLOB 				NULL,
	PRIMARY KEY (ID_SERIE)
);

CREATE TABLE LEARNING_ENGLISH.SEASONS (
	ID_SEASON 		   INTEGER NOT NULL AUTO_INCREMENT,
	SERIE 					   INTEGER NOT NULL,
	PRIMARY KEY (ID_SEASON),
	FOREIGN KEY(SERIE) REFERENCES LEARNING_ENGLISH.SERIES(ID_SERIE)
);

CREATE TABLE LEARNING_ENGLISH.CHAPTERS (
	ID_CHAPTER 		   INTEGER 			NOT NULL AUTO_INCREMENT,
	SEASON 				   INTEGER 			NOT NULL,
	NAME 					   VARCHAR(255)	NOT NULL,
	URL						   VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID_CHAPTER),
	FOREIGN KEY(SEASON) REFERENCES LEARNING_ENGLISH.SEASONS(ID_SEASON)
);

CREATE TABLE LEARNING_ENGLISH.SENTENCES (
	ID_SENTENCE		   INTEGER 				NOT NULL AUTO_INCREMENT,
	CHAPTER 			   INTEGER 				NOT NULL,
	SPANISH				   VARCHAR(5000)	NOT NULL,
	ENGLISH				   VARCHAR(5000)	NOT NULL,
	AUDIO					   BLOB 					NULL,
	AUDIO_NAME		   VARCHAR(255)		NULL
	PRIMARY KEY (ID_SENTENCE),
	FOREIGN KEY(CHAPTER) REFERENCES LEARNING_ENGLISH.CHAPTERS(ID_CHAPTER)
);
